### ISSUE TITLE
Monitor gateway timeout - traefik ?

### ISSUE THREAD

**Issue by iangregsondev** [KualiCo/nats-streaming-console#14]
Hi,

I got it working via the IP but I tried to configure it via traefik and i get gateway timeout.

Anybody managed to get it working ?

```
version: "3.1"

services:
  nats-streaming:
    image: nats-streaming:latest
    restart: always
    command: ["--store", "file", "--dir", "./data", "-m", "8222"]
    volumes:
      - nats-streaming-volume:/data
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  nats-streaming-console:
    build:
      context: ./nats-streaming-console
      dockerfile: Dockerfile
    environment:
      - STAN_URL=nats://nats-streaming:4222
      - STAN_MONITOR_URL=http://nats-streaming:8222

    labels:
      - traefik.port=8282
      - traefik.frontend.rule=Host:monitor.mytestdomain.com
      - traefik.frontend.entryPoints=https,http

volumes:
  nats-streaming-volume:

networks:
  external:
    external: true
```

I know traefik is only an http proxy, and thats all that i am trying to do. Proxy the console web app.

Any ideas ?

I am at a loss

Thanks in advance
