### ISSUE TITLE
Error "Not here."

### ISSUE THREAD

**Issue by upstream-team** [KualiCo/nats-streaming-console#7]
Try go to http://localhost:8282/ -> redirect -> http://localhost:8282/server
Response body: Not here.

WTF?

**Comment by 4lun** [comment]
@upstream-nsk I just had the same issue. In my case it was because [monitoring](https://nats.io/documentation/server/gnatsd-monitoring/) wasn't enabled on the server.

With my local instance, I was able to resolve it by running the server with:
```
go run nats-streaming-server.go -m 8222
```

**Comment by salisbury-espinosa** [comment]
@upstream-nsk i have same issue in docker way...
so after build from source 
```
git clone https://github.com/KualiCo/nats-streaming-console.git
cd nats-streaming-console
npm install
npm run build-css
npm run build
node server
```
everything is fixed 
 @tvalletta need update docker image
```
$ docker exec -ti nats-streaming-console_1 sh
/usr/src/app # cat ./server/nats-ss.js 
const { getInstance: getNerveInstance } = require('nats-nerve')

const defaults = {
  server: 'nats://localhost:4222',
  monitor: 'http://localhost:8222',
  cluster: 'test-cluster',
  appName: 'nats-streaming-console'
}
```

so `nats-ss.js` not load env variables for server, monitor and  cluster
https://github.com/KualiCo/nats-streaming-console/blob/master/server/nats-ss.js#L4

  @upstream-nsk use this https://hub.docker.com/r/mozgoo/nats-streaming-console/ (this is built on the top of master nats-streaming-console)
example configuration `docker-compose`:
```
version: '3'

services:
    nats-streaming-console:
      image: mozgoo/nats-streaming-console:latest
      environment:
        - STAN_URL=nats://nats-streaming:4222
        - STAN_MONITOR_URL=http://nats-streaming:8222
      ports:
        - 8282:8282

    nats-streaming:
      image: nats-streaming:0.11.2-linux
      ports:
        - 4222:4222
        - 8222:8222
```
